clear all;
clc;
a=imread('c:\paisaje.jpg');
b=rgb2gray(a);
c=b*1.4;
d=b+90;
subplot(2,3,1);
imshow(b);
title('Imagen a escala de grises');
subplot(2,3,2);
imshow(c);
title('Imagen contraste aumentado 40%');
subplot(2,3,3);
imshow(d);
title('Imagen con iluminacion aumentad 100%');
subplot(2,3,4);
imhist(b);
title('Histograma escala de grises');
subplot(2,3,5);
imhist(c);
title('Histograma contraste 40%');
subplot(2,3,6);
imhist(d);
title('Histograma con iluminacion aumentad 100%');